### ISSUE TITLE
Doesn't work with the sample from the stream

### ISSUE THREAD

**Issue by shplamana** [proEndreeper/Fallout76CodeBreaker#1]
I tried the code from the stream, but it seems like some validation isn't working correctly:
![sketch 2](https://user-images.githubusercontent.com/8671384/48388795-4a551780-e6c0-11e8-94b1-16ec281ec025.png)

**Comment by WaGi-Coding** [comment]
can confirm this is not working since it thinks you need unique Numbers/Letters

**Comment by proEndreeper** [comment]
Would like to note that this issue has been resolved, I fixed this issue in [this commit](https://github.com/proEndreeper/Fallout76CodeBreaker/commit/3edd5c516e25053ec90c2cd7dc9b2e460c508d92).
