### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by WaGi-Coding** [proEndreeper/Fallout76CodeBreaker#2]
http://prntscr.com/llikxx

the code to launch should be 63362650 but it shows me no code/s, only the keyword.

**Comment by proEndreeper** [comment]
Huh, that's strange, I'll check into why it's not working, as it works in Chrome but not Firefox.

**Comment by proEndreeper** [comment]
Alright, I've fixed the issue with it failing to successfully find the code.

Please let me know if the bug still happens for you. 

Thanks.
